apiVersion: apps/v1
kind: Deployment
metadata:
  name: da-bubble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: da-bubble
  template:
    metadata:
      labels:
        app: da-bubble
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: da-bubble
        image: ghcr.io/a-marbach/da-bubble:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"