apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: da-bubble
spec:
  ingressClassName: nginx
  rules:
  - host: da-bubble.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: da-bubble
            port:
              number: 80
